from selenium import webdriver

class AddUser:
        DR=webdriver.Chrome("C:\\Selenium\\chromedriver.exe")
        DR.get("http://127.0.0.1/orangehrm-3.3.1/symfony/web/index.php/auth/login")
        username=DR.find_element_by_id("txtUsername")
        username.send_keys("ankur")
        password=DR.find_element_by_id("txtPassword")
        password.send_keys("ankur")
        login.click()
	clickadmin=DR.find_element_by_id("menu_admin_viewAdminModule")
	clickadmin.click()
	clickaddbtn=DR.find_element_by_id("btnAdd")
	clickaddbtn.click()
	empname=DR.find_element_by_id("systemUser_employeeName_empName")
	empname.send_Keys("Ankur Kumar")
	username=DR.find_element_by_id("systemUser_userName")
	username.send_keys("ankur_04")
	password=DR.find_element_by_id("systemUser_password")
	password.send_keys("ankur_04")
	confirmedpassword=DR.find_element_by_id("systemUser_confirmPassword")
	confirmedpassword.send_Keys("ankur_04")
	savebtn=DR.find_element_by_id("btnSave")
	savebtn.click()	
